config/routes.rb
Rails.application.routes.draw do

get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'

resources :stations
resources :lines
resources :stops
resources :users , :except => [:index]
resources :sessions, :except => [:index]
end

app/models/line.rb
class Line < ActiveRecord::Base
  validates :name, :presence => true
  has_many :stations, through: :stops
  has_many :stops
end

app/models/station.rb
class Station < ActiveRecord::Base
  validates :name, :presence => true
  has_many :lines, through: :stops
  has_many :stops
end

app/models/stop.rb
class Stop < ActiveRecord::Base
  # validates :name, :presence => true
  belongs_to :station
  belongs_to :line
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name , presence: true
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
   def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path, alert: "Not RIGHT" if current_user.nil?
  end

end

app/controllers/lines_controller.rb
class LinesController < ApplicationController

  def index
    @line = Line.new
    @lines = Line.all
  end

  def new
    @line = Line.new
  end

  def create
    @line = Line.new(params_line)
    if @line.save
      flash[:notice] = "Line saved!!"
      redirect_to lines_path
    else
      render 'new'
    end
  end

  def show
    @station = Station.new
    @stops = Stop.all
    @line = Line.find(params[:id])
  end

  def edit
    @line = Line.find(params[:id])
  end

  def update
    @line = Line.find(params[:id])
    if @line.update(params_line)
      flash[:notice] = "Line has been updated."
      redirect_to lines_path
    else
      render 'edit'
    end
  end

  def destroy
    @line = Line.find(params[:id])
    @line.destroy
    flash[:notice] = "The line has been deleted"
    redirect_to lines_path
  end


private
  def params_line
    params.require(:line).permit(:name, station_ids:[])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
  user = User.find_by_name(params[:name])
  if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to stops_path, notice: "LOGGED IN"
  else
    flash.now.alert = "Name or password is invalid"
    render 'new'
  end
end

def destroy
  session[:user_id] = nil
  redirect_to stops_path, notice: "Logged out."
end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController

  def index
    @stations = Station.all
  end

  def new
    @station = Station.new
  end

  def show
    @station = Station.find(params[:id])
    @stops = Stop.all
  end

  def create
    @station = Station.new(params_station)
    if @station.save
      flash[:notice] = "Station saved."
      redirect_to stations_path
    else
      render 'new'
    end
  end

  def edit
    @station = Station.find(params[:id])
  end

  def update
    @station = Station.find(params[:id])
    if @station.update(params_station)
      flash[:notice] = "Station has been updated."
      redirect_to stations_path
    else
      render 'edit'
    end
  end

  def destroy
    @station = Station.find(params[:id])
    @station.destroy
    flash[:notice] = "Your station has been deleted"
    redirect_to stations_path
  end

  private
  def params_station
    params.require(:station).permit(:name, line_ids:[])
  end

end

app/controllers/stops_controller.rb
class StopsController < ApplicationController

  def index
    @stops = Stop.all
  end

  def new
    @stop = Stop.new
  end

  def show
    @stops = Stop.all
    @line = Line.new
    @station = Station.new
    @stop = Stop.find(params[:id])
  end

  def edit
    @lines = Line.all
    @stations = Station.all
    @stop = Stop.find(params[:id])
  end

  def update
    @stop = Stop.find(params[:id])
    if @stop.update(params_stops)
      flash[:notice] = "Your stop has been updated fool"
      redirect_to stops_path(@stop)
    else
      render 'show'
    end
  end


  def create
    @stop = Stop.new(params_stops)
    if @stop.save
      flash[:notice] = "Stop saved!!"
      redirect_to stops_path
    else
      render 'new'
    end
  end

  def destroy
    @stop = Stop.find(params[:id])
    @stop.destroy
    flash[:notice] = "Your stop has been deleted"
    redirect_to stops_path
  end


private
  def params_stops
    params.require(:stop).permit(:station_id, :line_id, :name)
  end
end




# <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    session[:user_id] = @user.id
    flash[:notice] = "Thanks for signing up"
    redirect_to stops_path
  else
    render "new"
  end
end

private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <div id="user_header">

      <% if current_user %>
      Logged in as <%= current_user.name %>
      <%= link_to "Log Out", logout_path %>
      <% else %>
        <%= link_to "Sign Up", signup_path %> or
        <%= link_to "Log In", login_path %>
      <% end %>
    </div>

<%= flash[:alert] %>
<%= flash[:notice] %>

<%= yield %>

   </div>
  </body>
</html>

app/views/lines/_form.html.erb
<%= render("layouts/errors", :object => @line) %>


<%= form_for(@line) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.collection_check_boxes :station_ids, Station.all, :id, :name %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/lines/edit.html.erb
<% content_for(:title, "Edit Line | Bus Timetable") %>

<h1>Edit Line</h1>

<%= render 'form' %>

app/views/lines/index.html.erb
<h1> Bus Lines </h1>

<ul>
  <% @lines.each do |line| %>
    <li><a href="lines/<%= line.id %>"><%= line.name %></a></li>
  <% end %>
</ul>



<%= link_to "Add New Line", new_line_path, :class => "btn btn-default" %>

<%= link_to "Station Menu", stations_path, :class => "btn btn-default" %>

<%= link_to "Stops Menu", stops_path, :class => "btn btn-default" %>

app/views/lines/new.html.erb
<% content_for(:title, "New Line | Bus Timetable") %>

<h1>New Line</h1>

<%= render 'form' %>

app/views/lines/show.html.erb
<h1><%= @line.name %></h1>
<h3> Lines: </h3>

<ul>
  <% @stops.each do |stop| %>
    <% if stop.line_id == @line.id %>
       <li><%= stop.station.name %></li>
      <% end %>
    <% end %>
  </ul>


<p><%= link_to "Edit", edit_line_path(@line), :class => "btn btn-info" %></p>
<p><%= link_to "Delete", line_path(@line),
                          :data => {:confirm => "You suuurreeeee?",
                          :method => "delete"},
                          :class => "btn btn-danger" %></p>

<%= link_to "Lines Menu", lines_path, :class => "btn btn-default" %>

<%= link_to "Stops Menu", stops_path, :class => "btn btn-default" %>

app/views/stations/_form.html.erb
<%= render("layouts/errors", :object => @station) %>


<%= form_for(@station) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.collection_check_boxes :line_ids, Line.all, :id, :name %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/stations/edit.html.erb
<% content_for(:title, "Edit Station | Bus Timetable") %>

<h1>Edit Station</h1>

<%= render 'form' %>

app/views/stations/index.html.erb
<h1> Stations </h1>

<ul>
  <% @stations.each do |station| %>
    <li><a href="stations/<%= station.id %>"><%= station.name %></a></li>
  <% end %>
</ul>

<%= link_to "Add New Station", new_station_path, :class => "btn btn-default" %>

<%= link_to "Lines Menu", lines_path, :class => "btn btn-default" %>

<%= link_to "Stops Menu", stops_path, :class => "btn btn-default" %>

app/views/stations/new.html.erb
<% content_for(:title, "New Station | Bus Timetable") %>

<h1>New Station</h1>

<%= render 'form' %>

app/views/stations/show.html.erb
<h1><%= @station.name %></h1>

<h3> Lines: </h3>
<ul>
  <% @stops.each do |stop| %>
    <% if stop.station_id == @station.id %>
    <li><%= stop.line.name %></li>
    <% end %>
  <% end %>


<p><%= link_to "Edit", edit_station_path(@station), :class => "btn btn-info" %></p>
<p><%= link_to "Delete", station_path(@station),
                          :data => {:confirm => "You suuurreeeee?",
                          :method => "delete"},
                          :class => "btn btn-danger" %></p>
<%= link_to "Lines Menu", lines_path, :class => "btn btn-default" %>

<%= link_to "Stops Menu", stops_path, :class => "btn btn-default" %>

app/views/stops/_form.html.erb
<% render("layouts/errors", :object => @stop) %>

<%= form_for(@stop) do |f| %>
  <div class="form-group">
<%= f.collection_select :station_id, Station.all, :id, :name %>
<%= f.collection_select :line_id, Line.all, :id, :name %>
  </div>
  <%= f.submit(:class => "btn btn-primary btn-lrg") %>
<% end %>

app/views/stops/edit.html.erb
<%= render("layouts/errors", :object => @stop) %>

<h1>Edit the stop fool</h1>

<%= render 'form' %>

app/views/stops/index.html.erb
<h1> Bus Stops </h1>

<p>Click a stop to edit the line or station</p>
<ul>
  <% @stops.each do |stop| %>
    <li><a href="stops/<%= stop.id %>"><%= stop.station.name + "\n\n\n|\n\n\n" + stop.line.name %></a></li>
   <% end %>
</ul>

<%= link_to "Add Stop", new_stop_path, :class => "btn btn-default" %>

<%= link_to "Line Menu", lines_path, :class => "btn btn-default" %>

<%= link_to "Station Menu", stations_path, :class => "btn btn-default" %>

app/views/stops/new.html.erb
<% content_for(:title, "New Stop | Bus Timetable") %>

<h1>New Stop</h1>

<%= render 'form' %>

app/views/stops/show.html.erb
<h1><%=  "Line:\n\n" + @stop.line.name + "\n-\n" +
    "Station:\n\n" + @stop.station.name %></h1>

<p><%= link_to "Edit", edit_stop_path(@stop), :class => "btn btn-info" %></p>
<p><%= link_to "Delete", stop_path(@stop),
                          :data => {:confirm => "You suuurreeeee?",
                          :method => "delete"},
                          :class => "btn btn-danger" %></p>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render 'form' %>